version: "3"
services:
  grafana:
    image: grafana/grafana:10.4.6
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - PROM_URL=${PROM_URL:-http://localhost:9090}
      - PROM_BASIC_AUTH=${PROM_BASIC_AUTH:-false}
      - PROM_BASIC_AUTH_USER=${PROM_BASIC_AUTH_USER:-}
      - PROM_BASIC_AUTH_PASS=${PROM_BASIC_AUTH_PASS:-}
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/etc/grafana/provisioning/dashboards/cortex
