# Cloudflare Tunnel Configuration for Cortex Structure Guard GitHub App
# This tunnel exposes the structure guard app running on localhost:3003

tunnel: insula-github-app
credentials-file: /Users/jamiecraik/.cloudflared/insula-github-app.json

# Ingress rules - traffic routing configuration
ingress:
  # Main application routes
  - hostname: insula-github.brainwav.io
    service: http://localhost:3003
    originRequest:
      # HTTP/2 support for better performance
      http2Origin: true
      # Connection timeout
      connectTimeout: 30s
      # TLS verification (skip for localhost)
      noTLSVerify: true
      # Keep-alive settings
      keepAliveConnections: 10
      keepAliveTimeout: 30s

  # Webhook endpoint (specific route for GitHub webhooks)
  - hostname: insula-github.brainwav.io
    path: /webhook
    service: http://localhost:3003
    originRequest:
      http2Origin: true
      connectTimeout: 10s
      noTLSVerify: true

  # Health check endpoint
  - hostname: insula-github.brainwav.io
    path: /health
    service: http://localhost:3003
    originRequest:
      http2Origin: true
      connectTimeout: 5s
      noTLSVerify: true

  # API endpoints
  - hostname: insula-github.brainwav.io
    path: /api/*
    service: http://localhost:3003
    originRequest:
      http2Origin: true
      connectTimeout: 30s
      noTLSVerify: true

  # Catch-all rule (required as the last rule)
  - service: http_status:404

# Tunnel-wide settings
retries: 3
grace-period: 30s

# Logging configuration
loglevel: info

# Metrics and monitoring (optional)
metrics: localhost:2000
