version: 2
updates:
  # GitHub Actions updates for security
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "jamiescottcraik"
    labels:
      - "dependencies"
      - "security"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
      include: scope
    allow:
      - dependency-type: direct
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
      include: scope
    allow:
      - dependency-type: direct
