name: 'Project Setup'
description: 'Setup Node.js and pnpm using mise and install dependencies'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version'
    required: false
    default: '9'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f
      with:
        path: |
          ~/.pnpm-store
          node_modules/.cache/nx
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
      with:
        tool_versions: |
          nodejs ${{ inputs.node-version }}
          pnpm ${{ inputs.pnpm-version }}
    - run: mise trust --yes .
      shell: bash
    - run: corepack enable
      shell: bash
    - run: pnpm install --frozen-lockfile
      shell: bash
