# markdownlint-cli2 configuration (YAML)
# See: https://github.com/DavidAnson/markdownlint-cli2#configuration

config:
  MD013:
    line_length: 140
    code_block_line_length: 9999
    heading_line_length: 100
    tables: false
    headings: true
    strict: false
  MD033:
    allowed_elements:
      - sup
# Other rules inherit defaults
