# markdownlint-cli2 configuration (YAML)
# See: https://github.com/DavidAnson/markdownlint-cli2#configuration

config:
  MD013:
    line_length: 140
    code_block_line_length: 9999
    heading_line_length: 100
    tables: false
    headings: true
    strict: false
  MD033:
    allowed_elements:
      - sup
      - img
  MD041:
    allow_preamble: true
# Other rules inherit defaults

# Ignore large, generated, or historical docs that do not conform to house style
ignores:
  - docs/engineering/**
  - docs/reports/**
  - docs/security/docker-security-audit.md
  - docs/security/PHASE4_FILE_INVENTORY.md
  - docs/GEMINI.md
  - docs/MLX_MODELS_COMPLETE.md
  - docs/protocol_v1.md
  - docs/README.md
