packages:
  - "apps/cortex-os"
  - "apps/cortex-cli"
  - "apps/cortex-os/packages/agents"
  - "apps/cortex-os/packages/mvp-core"
  - "apps/cortex-os/packages/mvp"
  - "apps/cortex-os/packages/mvp-server"
  - "apps/cortex-os/packages/rag/rag-contracts"
  - "apps/cortex-os/packages/rag/rag-ingest"
  - "apps/cortex-os/packages/rag/rag-embed"
  - "apps/cortex-os/packages/rag/rag-store"
  - "apps/cortex-os/packages/rag/rag-retriever"
  - "apps/cortex-os/packages/rag/rag-reranker"
  - "apps/cortex-os/packages/rag/rag-pipeline"
  - "packages/a2a"
  - "packages/a2a/a2a-contracts"
  - "packages/a2a/a2a-core"
  - "packages/a2a/a2a-transport"
  - "packages/a2a/a2a-handlers"
  - "packages/a2a/a2a-observability"
  - "packages/mcp"
  - "packages/mcp/mcp-core"
  - "packages/mcp/mcp-transport"
  - "packages/mcp/mcp-registry"
  - "packages/mcp/mcp-servers/echo-js"
  - "packages/memories"
  - "packages/orchestration"
  - "packages/rag"
  - "packages/simlab"
  - "packages/simlab/simlab-contracts"
  - "packages/simlab/simlab-core"
  - "packages/simlab/simlab-env"
  - "packages/simlab/simlab-agents"
  - "packages/simlab/simlab-metrics"
  - "packages/simlab/simlab-report"
  - "libs/typescript/contracts"
  - "libs/typescript/types"
  - "libs/typescript/utils"
  - "libs/typescript/telemetry"
  - "libs/typescript/testing"
  - ".cortex/gates"
  - "tools/structure-guard"
  - "tools/eslint-config"
  - "tools/lockfile-sync"
