packages:
  # Apps (ASBR structure)
  - 'apps/*'

  # Packages (shared libraries)
  - 'packages/*'
  - 'packages/model-gateway'

  # Nested packages within major packages
  - 'packages/a2a/a2a-*'
  - 'packages/mcp/mcp-*'

  # Services (backend services)
  - 'packages/orchestration/src/lib/outbox'
  - 'services/*'

  # Libraries (framework libraries)
  - 'libs/*'
  - 'libs/typescript/*'
  - 'libs/python/*'

  # External integrations
  - 'external/*'
