packages:
  # Apps (ASBR structure)
  - "apps/*"
  
  # Packages (shared libraries)
  - "packages/*"
  
  # Services (backend services)
  - "services/*"
  
  # Libraries (framework libraries)
  - "libs/*"
  - "libs/typescript/*"
  - "libs/python/*"
  
  # External integrations
  - "external/*"

excludes:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/tmp/**"
  - "**/temp/**"
