packages:
  - "apps/*"
  - "apps/*/frontend"
  - "apps/*/backend"
  - "apps/*/packages/*"
  - "packages/*"
  - "packages/*/*"
  - "libs/typescript/*"
  - "website"
neverBuiltDependencies: []
packageImportMethod: auto
