packages:
  - "apps/cortex-os"
  - "apps/cortex-os/packages/agents"
  - "apps/cortex-os/packages/mvp"
  - "apps/cortex-os/packages/mvp-server"
  - "packages/a2a"
  - "packages/mcp"
  - "packages/memories"
  - "packages/orchestration"
  - "packages/rag"
  - "packages/simlab"
  - "libs/typescript/contracts"
  - "libs/typescript/types"
  - "libs/typescript/utils"
  - "libs/typescript/telemetry"
  - "libs/typescript/testing"
  - "tools/structure-guard"
  - "tools/eslint-config"
  - "tools/lockfile-sync"
