[project]
name = "mcp-python"
version = "0.1.0"
requires-python = ">=3.11"
description = "Minimal MCP Python sidecar for Cortex-OS (local/dev only)"
authors = [ { name = "Cortex" } ]
license = { text = "MIT" }

dependencies = [
  "pexpect==4.8.0",
  "scancode-toolkit==32.2.0",
  "pytest==7.4.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
