version: 1.0.0
metadata:
  name: Security Danger Patterns
  description: Common security vulnerabilities and dangerous patterns
  author: Cortex OS
  updated: '2025-08-03'
rules:
  - id: HARDCODED_SECRET
    name: Hardcoded Secret
    description: Potential hardcoded secret or API key
    severity: critical
    category: security
    patterns:
      - (api[_-]?key|apikey)\s*[=:]\s*['"][^'"\s]{10,}['"]
      - (secret|token|password)\s*[=:]\s*['"][^'"\s]{8,}['"]
      - (bearer|auth)\s*[=:]\s*['"][^'"\s]{20,}['"]
    fileTypes:
      - ts
      - js
      - py
      - java
      - go
      - cs
      - php
      - rb
    suggestion: Move secrets to environment variables or secure vault
    cwe:
      - CWE-798
    owasp:
      - A02:2021
  - id: SQL_INJECTION
    name: SQL Injection Risk
    description: Potential SQL injection vulnerability
    severity: high
    category: security
    patterns:
      - \+\s*['"]\s*SELECT\s+
      - \+\s*['"]\s*INSERT\s+
      - \+\s*['"]\s*UPDATE\s+
      - \+\s*['"]\s*DELETE\s+
    fileTypes:
      - ts
      - js
      - py
      - java
      - php
      - cs
    suggestion: Use parameterized queries or ORM
    cwe:
      - CWE-89
    owasp:
      - A03:2021
  - id: EVAL_USAGE
    name: Code Injection Risk
    description: Use of dangerous eval() function
    severity: high
    category: security
    patterns:
      - \beval\s*\(
      - \bexec\s*\(
      - \bFunction\s*\(
      - \bsetTimeout\s*\(\s*['"]
    fileTypes:
      - ts
      - js
      - py
    suggestion: Avoid eval() and similar dynamic code execution
    cwe:
      - CWE-94
    owasp:
      - A03:2021
  - id: DEBUG_CODE
    name: Debug Code in Production
    description: Debug or development code that should not be in production
    severity: medium
    category: development
    patterns:
      - console\.log\(
      - console\.debug\(
      - print\(
      - debugger;
      - 'TODO:'
      - 'FIXME:'
      - 'HACK:'
    fileTypes:
      - ts
      - js
      - py
      - java
      - cs
    excludePatterns:
      - test
      - spec
      - debug
    suggestion: Remove debug code before production deployment
