[project]
name = "gpl-tools-service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "Pillow==10.1.0",
  "python-jose[cryptography]==3.3.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
