version: '3.8'
services:
  neo4j:
    image: neo4j:5
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/password
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333'
