[package]
name = "codex-providers-ext"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "codex_providers_ext"
path = "src/lib.rs"

[dependencies]
codex-core = { path = "../core" }
