# Cloudflare Tunnel Configuration for Cortex MCP Server
# This tunnel exposes the MCP server running on localhost:3000

tunnel: mcp-brainwav
credentials-file: /Users/jamiecraik/.cloudflared/mcp-brainwav.json

# Ingress rules - traffic routing configuration
ingress:
  # Main MCP server routes
  - hostname: mcp.brainwav.io
    service: http://localhost:3000
    originRequest:
      # HTTP/2 support for better performance
      http2Origin: true
      # Connection timeout
      connectTimeout: 30s
      # TLS verification (skip for localhost)
      noTLSVerify: true
      # Keep-alive settings
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      # Headers to preserve
      originServerName: localhost

  # Health check endpoint
  - hostname: mcp.brainwav.io
    path: /health
    service: http://localhost:3000
    originRequest:
      http2Origin: true
      connectTimeout: 5s
      noTLSVerify: true

  # MCP protocol endpoints
  - hostname: mcp.brainwav.io
    path: /mcp/*
    service: http://localhost:3000
    originRequest:
      http2Origin: true
      connectTimeout: 60s
      noTLSVerify: true
      # Increase timeout for MCP operations
      keepAliveTimeout: 120s

  # API endpoints
  - hostname: mcp.brainwav.io
    path: /api/*
    service: http://localhost:3000
    originRequest:
      http2Origin: true
      connectTimeout: 30s
      noTLSVerify: true

  # WebSocket upgrades for real-time MCP
  - hostname: mcp.brainwav.io
    path: /ws
    service: http://localhost:3000
    originRequest:
      http2Origin: false
      connectTimeout: 10s
      noTLSVerify: true

  # Catch-all rule (required as the last rule)
  - service: http_status:404

# Logging configuration
loglevel: info

# Metrics and observability
metrics: localhost:8081
