# Cloudflare Tunnel Configuration for Cortex MCP (updated)
# Exposes:
#   * Main MCP service (including ChatGPT connector) on 3024
#   * Main app on 3000

# Use your **named** tunnel (UUID from `cloudflared tunnel list`)
tunnel: 8109c0a4-6704-4119-b38e-5faa28f0903e
credentials-file: /Users/jamiecraik/.cloudflared/8109c0a4-6704-4119-b38e-5faa28f0903e.json

# Ingress routing
ingress:
  # 1) Fixed MCP core service (Python) on port 3024
  - hostname: cortex-mcp.brainwav.io
    service: http://127.0.0.1:3024
    originRequest:
      http2Origin: true
      connectTimeout: 30s
      noTLSVerify: true
      keepAliveConnections: 16
      keepAliveTimeout: 90s

  # 2) Main MCP web/dashboard (if still required) on port 3000
  - hostname: mcp.brainwav.io
    service: http://127.0.0.1:3000
    originRequest:
      http2Origin: true
      connectTimeout: 30s
      noTLSVerify: true
      keepAliveConnections: 16
      keepAliveTimeout: 90s


  # 4) Fallback 404 (must be last)
  - service: http_status:404

# Logging & metrics
loglevel: info
metrics: 127.0.0.1:8081
