version: '3.8'

services:
  # MCP Registry Service
  mcp-registry:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../packages/mcp-registry:/app
      - ../packages/mcp-core:/mcp-core
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024
    command: sh -c "cd /app && pnpm install && pnpm build && node dist/index.js"
    ports:
      - "3002:3002"
    networks:
      - cortex-network
    mem_limit: 1024m
    mem_reservation: 512m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Bridge Service
  mcp-bridge:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../packages/mcp-bridge:/app
      - ../packages/mcp-core:/mcp-core
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024
    command: sh -c "cd /app && pnpm install && pnpm build && node dist/index.js"
    ports:
      - "3003:3003"
    networks:
      - cortex-network
    mem_limit: 1024m
    mem_reservation: 512m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Core Service
  mcp-core:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../packages/mcp-core:/app
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024
    command: sh -c "cd /app && pnpm install && pnpm build && node dist/index.js"
    ports:
      - "3010:3010"
    networks:
      - cortex-network
    mem_limit: 1024m
    mem_reservation: 512m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  cortex-network:
    driver: bridge
