maps:
  cortex.node.cmd_injection.child_process: ["ATLAS:T0034-IndirectInjection","ATLAS:T0009-PromptInjection"]
  cortex.node.eval_like: ["ATLAS:T0019-ExecutionHijack"]
  cortex.web.untrusted_url_request: ["ATLAS:T0012-SSRF","ATLAS:T0021-DataExfiltration"]
  cortex.path.traversal.join: ["ATLAS:T0020-FileManipulation"]
  cortex.llm.insecure_tool_invocation: ["ATLAS:T0009-PromptInjection","ATLAS:T0031-ToolAbuse"]
  cortex.secrets.generic_aws: ["ATLAS:T0021-DataExfiltration"]
  cortex.template.injection.unsafe_interpolation: ["ATLAS:T0018-TemplateInjection"]
  cortex.zod.schema.missing: ["ATLAS:T0031-ToolAbuse"]
  cortex.py.subprocess.shell_true: ["ATLAS:T0034-IndirectInjection"]
  cortex.py.eval_exec: ["ATLAS:T0019-ExecutionHijack"]
  cortex.py.yaml.unsafe_load: ["ATLAS:T0026-InsecureDeserialization"]
  cortex.py.pickle.loads: ["ATLAS:T0026-InsecureDeserialization"]
  cortex.py.requests.untrusted_url: ["ATLAS:T0012-SSRF","ATLAS:T0021-DataExfiltration"]
  cortex.py.path.traversal.open: ["ATLAS:T0020-FileManipulation"]
  cortex.py.llm.insecure_tool_invocation: ["ATLAS:T0031-ToolAbuse","ATLAS:T0009-PromptInjection"]
  cortex.py.secrets.aws: ["ATLAS:T0021-DataExfiltration"]
  cortex.pydantic.schema.missing: ["ATLAS:T0031-ToolAbuse"]
