maps:
  cortex.node.cmd_injection.child_process: ["A03:2021-Injection"]
  cortex.node.eval_like: ["A03:2021-Injection","A04:2021-Insecure Design"]
  cortex.web.untrusted_url_request: ["A10:2021-Server-Side Request Forgery (SSRF)"]
  cortex.path.traversal.join: ["A01:2021-Broken Access Control"]
  cortex.llm.insecure_tool_invocation: ["A04:2021-Insecure Design","A05:2021-Security Misconfiguration"]
  cortex.secrets.generic_aws: ["A02:2021-Cryptographic Failures"]
  cortex.template.injection.unsafe_interpolation: ["A03:2021-Injection"]
  cortex.zod.schema.missing: ["A04:2021-Insecure Design"]
  cortex.py.subprocess.shell_true: ["A03:2021-Injection"]
  cortex.py.eval_exec: ["A03:2021-Injection"]
  cortex.py.yaml.unsafe_load: ["A08:2021-Software and Data Integrity Failures"]
  cortex.py.pickle.loads: ["A08:2021-Software and Data Integrity Failures"]
  cortex.py.requests.untrusted_url: ["A10:2021-Server-Side Request Forgery (SSRF)"]
  cortex.py.path.traversal.open: ["A01:2021-Broken Access Control"]
  cortex.py.llm.insecure_tool_invocation: ["A04:2021-Insecure Design","A05:2021-Security Misconfiguration"]
  cortex.py.secrets.aws: ["A02:2021-Cryptographic Failures"]
  cortex.pydantic.schema.missing: ["A04:2021-Insecure Design"]
