# OrbStack optimized development environment for Cortex-OS
# Profiles: dev-min, dev-full, web, api, workers, observability

x-orbstack-labels: &orbstack-labels
  orbstack.optimize: "true"
  orbstack.platform: "linux/arm64,linux/amd64"

services:
  nats:
    container_name: cortexos_nats
    image: nats:2.10
    command: ["-js", "-sd", "/data"]
    ports:
      - "${NATS_PORT:-4222}:4222"
      - "${NATS_MANAGEMENT_PORT:-8222}:8222"
    volumes:
      - nats:/data
    mem_limit: "256m"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    labels:
      <<: *orbstack-labels
      orbstack.service: "nats"
      orbstack.tier: "messaging"
      orbstack.project: "cortex-os"
      orbstack.description: "NATS messaging server with JetStream"
      orbstack.profile: "dev-min,dev-full"

  model-gateway:
    container_name: cortexos_model_gateway
    build:
      context: ../../
      dockerfile: packages/model-gateway/Dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
    profiles: ["dev-min","dev-full"]
    environment:
      # MLX runs host-native (Metal) on macOS; OrbStack exposes host via host.docker.internal
      MLX_BASE_URL: "${MLX_HOST_URL:-http://host.docker.internal:8081}"
      NODE_ENV: development
      # Constrain Node heap to reduce memory usage
      NODE_OPTIONS: "--max-old-space-size=384"
      MODEL_GATEWAY_PORT: "8080"
    ports:
      - "${MODEL_GATEWAY_PORT:-8081}:8080"
    depends_on:
      nats:
        condition: service_healthy
    mem_limit: "512m"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      <<: *orbstack-labels
      orbstack.service: "model-gateway"
      orbstack.tier: "api"
      orbstack.node: "true"
      orbstack.project: "cortex-os"
      orbstack.description: "Model Gateway API for MLX integration"
      orbstack.profile: "dev-min,dev-full"

  mcp-registry:
    container_name: cortexos_mcp_registry
    build:
      context: ../../
      dockerfile: packages/mcp-registry/Dockerfile
    profiles: ["dev-full"]
    environment:
      NODE_ENV: development
      MCP_REGISTRY_PORT: "8090"
    ports:
      - "${MCP_REGISTRY_PORT:-8082}:8090"
    depends_on:
      nats:
        condition: service_healthy
    mem_limit: "256m"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8090/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      <<: *orbstack-labels
      orbstack.service: "mcp-registry"
      orbstack.tier: "api"
      orbstack.node: "true"
      orbstack.project: "cortex-os"
      orbstack.description: "Model Context Protocol Registry"
      orbstack.profile: "dev-full"

  cortex-os:
    container_name: cortexos_cortex_os
    build:
      context: ../../
      dockerfile: apps/cortex-os/Dockerfile
    profiles: ["dev-min","dev-full"]
    environment:
      NODE_ENV: development
      NATS_URL: "nats://nats:4222"
      MODEL_GATEWAY_URL: "http://model-gateway:8080"
      NODE_OPTIONS: "--max-old-space-size=384"
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      nats:
        condition: service_healthy
      model-gateway:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "2"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s
    labels:
      <<: *orbstack-labels
      orbstack.service: "cortex-os"
      orbstack.tier: "app"
      orbstack.node: "true"
      orbstack.project: "cortex-os"
      orbstack.description: "Main Cortex-OS runtime application"
      orbstack.profile: "dev-min,dev-full"

  agents-workers:
    container_name: cortexos_agents_workers
    build:
      context: ../../
      dockerfile: packages/agents/Dockerfile
    profiles: ["workers"]
    environment:
      NODE_ENV: development
      NATS_URL: "nats://nats:4222"
      NODE_OPTIONS: "--max-old-space-size=256"
    depends_on:
      nats:
        condition: service_healthy
    mem_limit: "384m"

  otel-collector:
    container_name: cortexos_otel_collector
    image: otel/opentelemetry-collector:0.103.1
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ../../docs/mcp/observability/otel-collector.yaml:/etc/otelcol/config.yaml:ro
    profiles: ["observability"]
    ports:
      - "${OTEL_HTTP_PORT:-4318}:4318"
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:4318"]
      interval: 10s
      timeout: 2s
      retries: 3
    labels:
      <<: *orbstack-labels
      orbstack.service: "otel-collector"
      orbstack.tier: "observability"
      orbstack.project: "cortex-os"
      orbstack.description: "OpenTelemetry metrics and traces collector"
      orbstack.profile: "observability"

  loki:
    container_name: cortexos_loki
    image: grafana/loki:2.9.8
    command: ["-config.file=/etc/loki/local-config.yaml"]
    profiles: ["observability"]
    ports:
      - "${LOKI_PORT:-3100}:3100"
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:3100/ready"]
      interval: 10s
      timeout: 2s
      retries: 3
    labels:
      <<: *orbstack-labels
      orbstack.service: "loki"
      orbstack.tier: "observability"
      orbstack.project: "cortex-os"
      orbstack.description: "Grafana Loki log aggregation system"
      orbstack.profile: "observability"

  tempo:
    container_name: cortexos_tempo
    image: grafana/tempo:2.5.0
    command: ["-config.file=/etc/tempo.yaml"]
    profiles: ["observability"]
    ports:
      - "${TEMPO_PORT:-3200}:3200"
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:3200/status"]
      interval: 10s
      timeout: 2s
      retries: 3
    labels:
      <<: *orbstack-labels
      orbstack.service: "tempo"
      orbstack.tier: "observability"
      orbstack.project: "cortex-os"
      orbstack.description: "Grafana Tempo distributed tracing backend"
      orbstack.profile: "observability"

  grafana:
    container_name: cortexos_grafana
    image: grafana/grafana:10.4.3
    profiles: ["observability"]
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    depends_on:
      loki:
        condition: service_healthy
      tempo:
        condition: service_healthy
    volumes:
      - ../../infra/compose/observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ../../infra/compose/observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../../docs/mcp/observability/dashboards:/var/lib/grafana/dashboards:ro
    mem_limit: "512m"
    labels:
      <<: *orbstack-labels
      orbstack.service: "grafana"
      orbstack.tier: "observability"
      orbstack.project: "cortex-os"
      orbstack.description: "Grafana visualization and monitoring dashboard"
      orbstack.profile: "observability"

  cortex-web:
    container_name: cortexos_cortex_web
    build:
      context: ../../
      dockerfile: apps/cortex-web/Dockerfile
    profiles: ["web"]
    environment:
      NODE_ENV: development
      NODE_OPTIONS: "--max-old-space-size=384"
    ports:
      - "${WEB_PORT:-3000}:3000"
    mem_limit: "512m"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      <<: *orbstack-labels
      orbstack.service: "cortex-web"
      orbstack.tier: "web"
      orbstack.node: "true"
      orbstack.project: "cortex-os"
      orbstack.description: "Cortex-OS web frontend application"
      orbstack.profile: "web"

  api:
    container_name: cortexos_api
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile
    profiles: ["api"]
    environment:
      PYTHONUNBUFFERED: "1"
      APP_MODULE: "src.api.endpoints:app"
    ports:
      - "${API_PORT:-8080}:8082"
    mem_limit: "384m"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8082/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      <<: *orbstack-labels
      orbstack.service: "api"
      orbstack.tier: "api"
      orbstack.python: "true"
      orbstack.project: "cortex-os"
      orbstack.description: "Cortex-OS Python API backend"
      orbstack.profile: "api"

volumes:
  nats: {}
