# Bandit Security Configuration for Python
# Format: YAML configuration for bandit

# Directories to exclude from scanning
exclude_dirs:
  - ".venv"
  - "venv"
  - "__pycache__"
  - ".git"
  - "node_modules"
  - "dist"
  - "build"
  - ".artifacts"
  - "coverage"
  - "htmlcov"
  - "external"
  - ".pytest_cache"
  - ".mypy_cache"

# Test IDs to skip with justifications
skips:
  # Allow asserts in test files
  # Handle shell=True with custom safe_subprocess utility

# Test patterns to exclude
exclude:
  - "*/tests/*"
  - "*/test_*"
  - "*_test.py"
  - "*/conftest.py"

# Include all security-related tests
tests:
  - B101 # assert_used
  - B102 # exec_used
  - B103 # set_bad_file_permissions
  - B104 # hardcoded_bind_all_interfaces
  - B105 # hardcoded_password_string
  - B106 # hardcoded_password_funcarg
  - B107 # hardcoded_password_default
  - B108 # hardcoded_tmp_directory
  - B110 # try_except_pass
  - B112 # try_except_continue
  - B201 # flask_debug_true
  - B301 # pickle_load
  - B302 # marshal_load
  - B303 # md5
  - B304 # insecure_cipher
  - B305 # insecure_cipher_mode
  - B306 # insecure_mktemp
  - B307 # eval
  - B308 # mark_safe
  - B310 # urllib_urlopen
  - B311 # random
  - B312 # telnetlib
  - B313 # xml_bad_cElementTree
  - B314 # xml_bad_ElementTree
  - B315 # xml_bad_expatreader
  - B316 # xml_bad_expatbuilder
  - B317 # xml_bad_sax
  - B318 # xml_bad_minidom
  - B319 # xml_bad_pulldom
  - B320 # xml_bad_xmlparser
  - B321 # ftplib
  - B322 # input
  - B323 # unverified_context
  - B324 # hashlib_new_insecure_functions
  - B325 # tempnam
  - B501 # request_with_no_cert_validation
  - B502 # ssl_with_bad_version
  - B503 # ssl_with_bad_defaults
  - B504 # ssl_with_no_version
  - B505 # weak_cryptographic_key
  - B506 # yaml_load
  - B507 # ssh_no_host_key_verification
  - B601 # paramiko_calls
  - B602 # subprocess_popen_with_shell_equals_true
  - B603 # subprocess_without_shell_equals_false
  - B604 # any_other_function_with_shell_equals_true
  - B605 # start_process_with_a_shell
  - B606 # start_process_with_no_shell
  - B607 # start_process_with_partial_path
  - B608 # hardcoded_sql_expressions
  - B609 # linux_commands_wildcard_injection
  - B610 # django_extra_used
  - B611 # django_rawsql_used
  - B701 # jinja2_autoescape_false
  - B702 # use_of_mako_templates
  - B703 # django_mark_safe
