start: 2025-01-06
weeks:
  - target: packages/agents
    goal:
      lines: 90
      branches: 80
  - target: packages/mcp
    goal:
      lines: 90
      branches: 80
  - target: packages/rag
    goal:
      lines: 90
      branches: 80
  - target: packages/memories
    goal:
      lines: 90
      branches: 80
policy:
  global_floor:
    lines: 85
    branches: 70
  max_regression: 0
