# Performance monitoring and optimization configuration
# This file configures various performance monitoring tools and thresholds

# Bundle analysis thresholds
bundle:
  # Maximum bundle sizes (in KB)
  maxSizes:
    main: 500
    vendor: 1000
    async: 250

  # Performance budgets
  budgets:
    - type: bundle
      name: main
      baseline: 400
      maximumWarning: 450
      maximumError: 500

    - type: initial
      maximumWarning: 500
      maximumError: 600

# Memory monitoring
memory:
  # Heap size limits (in MB)
  warningThreshold: 1024
  errorThreshold: 2048

  # Garbage collection monitoring
  gcMetrics: true

  # Memory leak detection
  leakDetection:
    enabled: true
    interval: 30000 # 30 seconds
    threshold: 50 # MB growth per interval

# Performance metrics
metrics:
  # Core Web Vitals thresholds
  coreWebVitals:
    LCP: 2500 # Largest Contentful Paint (ms)
    FID: 100 # First Input Delay (ms)
    CLS: 0.1 # Cumulative Layout Shift
    FCP: 1800 # First Contentful Paint (ms)
    TTFB: 600 # Time to First Byte (ms)

  # Build performance
  build:
    warningThreshold: 60000 # 1 minute
    errorThreshold: 120000 # 2 minutes

  # Test performance
  test:
    unitTestTimeout: 5000
    integrationTestTimeout: 30000
    e2eTestTimeout: 60000

# Resource monitoring
resources:
  # CPU usage thresholds
  cpu:
    warning: 80
    error: 95

  # Network performance
  network:
    slowConnectionThreshold: 1000 # ms
    timeoutThreshold: 10000 # ms

  # Disk usage
  disk:
    warningThreshold: 85 # percentage
    errorThreshold: 95 # percentage

# Caching configuration
cache:
  # Build cache
  build:
    maxSize: 2048 # MB
    ttl: 86400 # 24 hours

  # Runtime cache
  runtime:
    maxEntries: 1000
    ttl: 3600 # 1 hour

  # CDN cache
  cdn:
    staticAssets: 31536000 # 1 year
    apiResponses: 300 # 5 minutes

# Alerts and notifications
alerts:
  # Performance degradation alerts
  performance:
    enabled: true
    thresholds:
      responseTime: 5000
      errorRate: 0.05
      availability: 0.99

  # Resource alerts
  resources:
    enabled: true
    channels:
      - console
      - file

  # Security alerts
  security:
    enabled: true
    severity: high
