global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # ML Inference Service
  - job_name: "ml-inference"
    static_configs:
      - targets:
          [
            "ml-inference-dev:8000",
            "ml-inference-prod:8000",
            "ml-inference-gpu:8000",
          ]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s

  # Ollama Service
  - job_name: "ollama"
    static_configs:
      - targets: ["ollama:11434"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node exporter for system metrics (if available)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
