# OrbStack Configuration for A2A Protocol Server
# Optimized for macOS development with OrbStack

version: '3.8'

services:
  a2a:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: a2a-protocol
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    networks:
      - default
    labels:
      # OrbStack specific labels
      - "orbstack.http.port=3000"
      - "orbstack.http.domain=a2a.local"
      - "orbstack.description=A2A Protocol Server - JSON-RPC 2.0"
      - "orbstack.icon=🤖"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

networks:
  default:
    name: a2a-network