name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-lint-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy, llvm-tools-preview

      - name: Cache cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-llvm-cov
        run: |
          cargo install cargo-llvm-cov || true

      - name: Format check
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --workspace --all-features -- -D warnings

      - name: Build
        run: cargo build --workspace --all-features --locked

      - name: Test
        run: cargo test --workspace --all-features --locked

      - name: Coverage (fail under 95% lines)
        run: cargo llvm-cov --workspace --all-features --fail-under-lines 95 --text
