[package]
name = "cortex-github"
version = "1.0.0"
edition = "2021"
description = "GitHub API client and operations for Cortex-OS"
license = "MIT OR Apache-2.0"

[dependencies]
# HTTP client (pin to avoid ICU/idna requiring newer rustc)
reqwest = { version = "=0.11.18", features = [
    "json",
    "stream",
], default-features = false }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async runtime
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
futures = "0.3"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
tracing = "0.1"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Base64 encoding (align with cortex-code)
base64 = "0.21"

# URL parsing (compat across workspace)
url = "2"

# Cryptography for webhook verification
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"

# Random number generation
rand = "0.8"

# HTTP types
bytes = "1.0"

# UUID generation
uuid = { version = "1.0", features = ["v4", "serde"] }

# A2A integration (workspace dependency)
# cortex-a2a-core = { path = "../a2a/a2a-core" }

[dev-dependencies]
# Testing utilities
mockito = "1.4"
tempfile = "3"
tokio-test = "0.4"
insta = "1.34"

[features]
default = ["a2a-integration"]
a2a-integration = []
