[project]
name = "cortex-rag"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "torch>=2.0.0",
  "transformers>=4.30.0",
  "numpy>=1.21.0",
  "mlx>=0.0.10",
  "mlx-lm>=0.1.0",
  "pdfplumber>=0.9.0",
  "python-docx>=0.8.11",
  "python-pptx>=0.6.21",
  "openpyxl>=3.1.0",
  "beautifulsoup4>=4.12.0",
  "lxml>=4.9.0",
  "pytesseract>=0.3.10",
  "Pillow>=9.0.0",
  "openai-whisper>=20231106",
  "pydub>=0.25.1",
  "requests>=2.31.0",
  "selenium>=4.15.0",
  "playwright>=1.40.0",
  "tree-sitter>=0.20.0",
  "tree-sitter-languages>=1.8.0",
  "neo4j>=5.14.0",
  "jsonschema>=4.19.0",
  "pyyaml>=6.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
