version: '3.8'

services:
  # Test database with seeding
  test-db:
    image: sqlite:latest
    container_name: cortex-webui-test-db
    volumes:
      - test-db-data:/data
      - ./tests/fixtures:/fixtures:ro
    environment:
      - SQLITE_DATABASE=cortex_test.db
    networks:
      - cortex-test-network

  # Redis for session management and caching
  test-redis:
    image: redis:7-alpine
    container_name: cortex-webui-test-redis
    ports:
      - "6380:6379"
    volumes:
      - test-redis-data:/data
    networks:
      - cortex-test-network

  # Local Memory service for testing
  test-local-memory:
    image: node:18-alpine
    container_name: cortex-webui-test-local-memory
    working_dir: /app
    ports:
      - "3028:3028"
    volumes:
      - ../../apps/cortex-os/packages/local-memory:/app
      - test-memory-data:/app/data
    environment:
      - NODE_ENV=test
      - PORT=3028
      - DATABASE_URL=file:/app/data/test-memory.db
      - JWT_SECRET=test_jwt_secret_brainwav
      - CORS_ORIGIN=http://localhost:3000
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - test-db
    networks:
      - cortex-test-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3028/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend service for testing
  test-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cortex-webui-test-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - test-uploads:/app/uploads
      - test-data:/app/data
    environment:
      - NODE_ENV=test
      - PORT=3001
      - DATABASE_PATH=/app/data/cortex_test.db
      - REDIS_URL=redis://test-redis:6379
      - LOCAL_MEMORY_URL=http://test-local-memory:3028/api/v1
      - JWT_SECRET=test_jwt_secret_brainwav
      - FRONTEND_URL=http://localhost:3000
      - CORS_ORIGIN=http://localhost:3000
      - LOG_LEVEL=debug
      - TELEMETRY_ENABLED=false
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX=1000
    depends_on:
      test-db:
        condition: service_started
      test-redis:
        condition: service_started
      test-local-memory:
        condition: service_healthy
    networks:
      - cortex-test-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Frontend service for testing
  test-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cortex-webui-test-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/dist:/app/dist
    environment:
      - NODE_ENV=test
      - VITE_API_BASE_URL=http://test-backend:3001/api
      - VITE_LOCAL_MEMORY_URL=http://test-local-memory:3028/api/v1
      - VITE_BRAND_NAME=brAInwav Cortex-OS
      - VITE_DEBUG_MODE=true
    depends_on:
      test-backend:
        condition: service_healthy
    networks:
      - cortex-test-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Mock AI service for testing
  test-ai-service:
    image: node:18-alpine
    container_name: cortex-webui-test-ai
    working_dir: /app
    ports:
      - "3030:3030"
    volumes:
      - ./tests/mocks/ai-service:/app
    environment:
      - NODE_ENV=test
      - PORT=3030
      - MOCK_RESPONSES=true
    command: >
      sh -c "npm install && node index.js"
    networks:
      - cortex-test-network

  # File processing service for testing
  test-file-service:
    image: node:18-alpine
    container_name: cortex-webui-test-file-processor
    working_dir: /app
    ports:
      - "3031:3031"
    volumes:
      - ./tests/mocks/file-service:/app
      - test-uploads:/app/uploads
    environment:
      - NODE_ENV=test
      - PORT=3031
      - UPLOAD_DIR=/app/uploads
    command: >
      sh -c "npm install && node index.js"
    depends_on:
      - test-backend
    networks:
      - cortex-test-network

  # Selenium Grid for browser testing
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: cortex-webui-selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - cortex-test-network

  # Chrome node for Selenium Grid
  selenium-chrome:
    image: selenium/node-chrome:4.15.0
    container_name: cortex-webui-selenium-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSION=4
    networks:
      - cortex-test-network

  # Firefox node for Selenium Grid
  selenium-firefox:
    image: selenium/node-firefox:4.15.0
    container_name: cortex-webui-selenium-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSION=4
    networks:
      - cortex-test-network

volumes:
  test-db-data:
    driver: local
  test-redis-data:
    driver: local
  test-memory-data:
    driver: local
  test-uploads:
    driver: local
  test-data:
    driver: local

networks:
  cortex-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16