version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://backend:3001/api
    depends_on:
      - backend
    networks:
      - cortex-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret_here
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_PATH=/app/data/cortex.db
    volumes:
      - cortex-data:/app/data
      - cortex-uploads:/app/uploads
    networks:
      - cortex-network

volumes:
  cortex-data:
  cortex-uploads:

networks:
  cortex-network:
    driver: bridge
