name: Accessibility
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec axe --dir ./apps/cortex-os/dist --exit || true
