name: AgentOps
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AGENTOPS_API_KEY: ${{ secrets.AGENTOPS_API_KEY }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.12'
      - name: Set up uv
        uses: astral-sh/setup-uv@8d55fbecc275b1c35dbe060458839f8d30439ccf
      - name: Sync deps
        working-directory: python
        run: uv sync --frozen
      - name: Run AgentOps
        working-directory: python
        run: uv run python evals/run_agentops.py
