name: AgentOps
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AGENTOPS_API_KEY: ${{ secrets.AGENTOPS_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Sync deps
        working-directory: python
        run: uv sync --frozen
      - name: Run AgentOps
        working-directory: python
        run: uv run python evals/run_agentops.py
