name: AgentOps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

permissions:
  contents: read

concurrency:
  group: agentops-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AGENTOPS_API_KEY: ${{ secrets.AGENTOPS_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python with uv
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            python/.venv
          key: ${{ runner.os }}-python-3.12-${{ hashFiles('python/pyproject.toml', 'python/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-3.12-
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
      - name: Sync deps
        working-directory: python
        run: uv sync --frozen
      - name: Run AgentOps
        working-directory: python
        run: uv run python evals/run_agentops.py
