name: Assistant Router

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened, assigned]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write
  actions: read

jobs:
  route:
    runs-on: ubuntu-latest
    steps:
      - name: Check trigger
        id: check
        run: |
          BODY=$(jq -r '.comment.body // .review.body // .issue.body // ""' <<< '${{ toJson(github.event) }}')
          TITLE=$(jq -r '.issue.title // ""' <<< '${{ toJson(github.event) }}')
          echo "BODY=$BODY" >> $GITHUB_OUTPUT
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT

      - name: Route to services via Cloudflared
        if: contains(steps.check.outputs.BODY, '@cortex') || contains(steps.check.outputs.BODY, '@semgrep') || contains(steps.check.outputs.BODY, '@insula') || contains(steps.check.outputs.TITLE, '@cortex') || contains(steps.check.outputs.TITLE, '@semgrep') || contains(steps.check.outputs.TITLE, '@insula')
        env:
          ROUTER_SECRET: ${{ secrets.ASSISTANT_ROUTER_SECRET }}
          AI_URL: ${{ secrets.CLOUDFLARED_AI_URL }}
          SEMGREP_URL: ${{ secrets.CLOUDFLARED_SEMGREP_URL }}
          STRUCTURE_URL: ${{ secrets.CLOUDFLARED_STRUCTURE_URL }}
        run: |
          set -euo pipefail
          EVENT='${{ toJson(github.event) }}'
          SIG=$(printf "%s" "$EVENT" | openssl dgst -sha256 -hmac "$ROUTER_SECRET" | sed 's/^.* //')
          # Post to each target if mentioned
          route() {
            URL=$1
            [ -z "$URL" ] && exit 0
            curl -sS -X POST "$URL/webhook" \
              -H "X-GitHub-Event: custom" \
              -H "X-GitHub-Delivery: ${{ github.run_id }}-${{ github.run_number }}" \
              -H "X-Hub-Signature-256: sha256=$SIG" \
              -H 'Content-Type: application/json' \
              --data "$EVENT" | cat
          }

          BODY='${{ steps.check.outputs.BODY }}'
          TITLE='${{ steps.check.outputs.TITLE }}'

          if echo "$BODY $TITLE" | grep -qi '@cortex'; then route "$AI_URL"; fi
          if echo "$BODY $TITLE" | grep -qi '@semgrep'; then route "$SEMGREP_URL"; fi
          if echo "$BODY $TITLE" | grep -qi '@insula'; then route "$STRUCTURE_URL"; fi
