name: Chaos Testing
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  chaos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stress-ng
        run: sudo apt-get update && sudo apt-get install -y stress-ng
      - name: Run CPU stress test
        run: stress-ng --cpu 2 --timeout 60
