name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm structure:validate
      - name: Check packages for circular deps
        run: |
          pnpm madge --circular --extensions ts,tsx ./packages || {
            echo "madge detected issues in packages"
            exit 1
          }
        continue-on-error: true
      - name: Check apps for circular deps
        run: |
          pnpm madge --circular --extensions ts,tsx ./apps || {
            echo "madge detected issues in apps"
            exit 1
          }
        continue-on-error: true
      - run: |
          pnpm eslint --ext .ts,.tsx --rule "import/no-restricted-paths: error"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install --frozen-lockfile
      - name: Sync Python dependencies
        run: |
          uv sync || {
            echo "uv sync failed"
            exit 1
          }
        continue-on-error: true
      - run: pnpm test -- --coverage
      - name: Run Python tests
        run: |
          uv run pytest --cov=services --cov=libs/python || {
            echo "pytest failed"
            exit 1
          }
        continue-on-error: true
      - name: Check coverage thresholds
        run: |
          pnpm nyc check-coverage --lines 80 --functions 80 --branches 70 || {
            echo "coverage check failed"
            exit 1
          }
        continue-on-error: true
