name: ci
on:
  push: { branches: ["main"] }
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          node-version: '22'
          pnpm-version: '9'
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test:coverage:threshold
      - run: pnpm build

  bun-lane:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
        with:
          tool_versions: |
            nodejs 22
            bun 1.2.2
      - run: bun -v
      - run: bun install --frozen-lockfile || true
      - run: bun run -T nx run-many -t test --parallel || true
