name: ci
on:
  push: { branches: ["main"] }
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: corepack enable
      - run: pnpm -v
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm build

  bun-lane:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: bun -v
      - run: bun install --frozen-lockfile || true
      - run: bun run -T nx run-many -t test --parallel || true
