name: Compliance

on:
  pull_request:
  push:
    branches: [main]

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: License validation
        run: pnpm license:validate
      - name: Upload license reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-report-${{ github.sha }}
          path: |
            reports/compliance/license-scan.json
            reports/compliance/license-scan.md
          if-no-files-found: warn
      - name: Generate SBOM
        run: pnpm sbom:generate
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: sbom/sbom.cdx.json
          if-no-files-found: error
