name: cortex-control-centre

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm tsx .cortex/tooling/check-structure.ts
      - run: pnpm tsx .cortex/tooling/check-agents.ts
      - run: pnpm tsx .cortex/tooling/check-index.ts

