name: Cortex Code Upstream Drift

on:
  schedule:
    - cron: "0 9 * * 1"   # Every Monday at 09:00 UTC
  workflow_dispatch: {}

jobs:
  upstream-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Check upstream status
        shell: bash
        run: |
          set -euo pipefail
          git -C external/openai-codex fetch origin --prune --tags -q || true
          LATEST=$(git -C external/openai-codex rev-list -1 origin/main -- codex-rs || echo "")
          RECORDED=""
          if [[ -f apps/cortex-code/UPSTREAM_REF ]]; then
            RECORDED=$(cat apps/cortex-code/UPSTREAM_REF)
          fi
          echo "Upstream latest codex-rs: ${LATEST:-unknown}"
          echo "Recorded baseline       : ${RECORDED:-none}"
          if [[ -n "$LATEST" && -n "$RECORDED" && "$LATEST" != "$RECORDED" ]]; then
            echo "::error::Upstream codex-rs advanced. Run 'nx run cortex-code:upstream:pull' to sync." >&2
            exit 1
          fi
          echo "No drift (or baseline not set)."

