name: Cortex TUI CI
on:
  push:
    paths:
      - 'apps/cortex-tui/**'
  pull_request:
    paths:
      - 'apps/cortex-tui/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      
      - name: Run tests
        working-directory: apps/cortex-tui
        run: cargo test --all-features
        
      - name: Check coverage
        working-directory: apps/cortex-tui
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --out Xml
          COVERAGE=$(cargo tarpaulin --print-summary | grep "Coverage" | awk '{print int($2)}')
          if [ "$COVERAGE" -lt 90 ]; then
            echo "Coverage ($COVERAGE%) below 90% threshold"
            exit 1
          fi
          echo "Coverage: $COVERAGE%"
          
      - name: Security audit
        working-directory: apps/cortex-tui
        run: |
          cargo install cargo-audit
          cargo audit
        
      - name: Clippy
        working-directory: apps/cortex-tui
        run: cargo clippy -- -D warnings
        
      - name: Check formatting
        working-directory: apps/cortex-tui
        run: cargo fmt --check