name: Cortex PR Review
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  models: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Diff
        run: |
          git diff origin/${{ github.base_ref }}..HEAD > pr.diff

      - name: Setup Cortex
        run: |
          curl -L https://github.com/${{ github.repository }}/releases/latest/download/cortex-linux-x64 -o cortex
          chmod +x cortex

      - name: Run Cortex Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CORTEX_PROVIDER: github-models
        run: |
          ./cortex review \
            --diff pr.diff \
            --output review.md

      - name: Post Review
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.md', 'utf8');
            await github.rest.pulls.createReview({
              ...context.repo,
              pull_number: context.issue.number,
              body: review,
              event: 'COMMENT'
            });
