name: Docs Lint

on:
  pull_request:
    paths:
      - 'docs/**/*.md'
      - '.markdownlint-cli2.yaml'
  push:
    branches: [ main ]
    paths:
      - 'docs/**/*.md'
      - '.markdownlint-cli2.yaml'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install markdownlint-cli2
        run: npm i -g markdownlint-cli2
      - name: Lint Markdown
        run: markdownlint-cli2 "docs/**/*.md"
