name: Docs Lint

on:
  pull_request:
    paths:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'
      - '.markdownlint*'
      - '.github/workflows/docs-lint.yml'
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'
      - '.markdownlint*'

jobs:
  curated:
    name: Curated Docs Lint (Blocking)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.3.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps (frozen lockfile)
        run: pnpm install --frozen-lockfile
      - name: Run curated docs lint
        run: pnpm docs:lint

  full-scan:
    name: Full Legacy Docs Scan (Non-Blocking)
    runs-on: ubuntu-latest
    needs: curated
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.3.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps (frozen lockfile)
        run: pnpm install --frozen-lockfile
      - name: Run full legacy scan
        run: pnpm docs:lint:all || true
      - name: Summarize legacy violations
        run: |
          pnpm docs:lint:all || true > docs-lint-all.txt
          echo '--- Legacy Docs Lint Summary (Top 30 Lines) ---' > summary.txt
          grep -E 'MD0|MD1|MD2|MD3|MD4' docs-lint-all.txt | head -30 >> summary.txt || true
          echo '\n(See full artifact for complete list)' >> summary.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: legacy-docs-lint-report
          path: |
            docs-lint-all.txt
            summary.txt
