name: MCP Python Integration (Transports)

on:
  pull_request:
    paths:
      - 'packages/cortex-mcp/**'
      - '.github/workflows/mcp-python-integration.yml'
  push:
    branches: ["main"]
    paths:
      - 'packages/cortex-mcp/**'
      - '.github/workflows/mcp-python-integration.yml'

jobs:
  python-mcp-integration:
    name: Python MCP transport tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and set Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Run FastMCP server tests
        working-directory: packages/cortex-mcp
        run: |
          uv run --no-sync \
            --with pytest \
            --with requests \
            pytest -q

  # Legacy Redis/Qdrant jobs removed: legacy Python MCP package deprecated
