name: MCP Nightly Full

on:
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: mcp-nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly:
    runs-on: ubuntu-latest
    env:
      CI_MCP_FULL: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      
      - name: Derive pnpm store path
        id: pnpm-store
        shell: bash
        run: echo "path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run full MCP interop tests
        run: |
          cd packages/mcp
          pnpm vitest run src/test/mixed-topology.e2e.test.ts
          pnpm vitest run src/lib/client.e2e.test.ts
      - name: Run MCP micro-benchmark (stdio)
        run: |
          node scripts/mcp-bench.mjs --mode stdio --cmd "node packages/mcp/mcp-servers/echo-js/dist/server.js" --n 200 --concurrency 16 | tee bench.json
      - name: Upload Bench Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-bench-nightly
          path: bench.json
