name: CI/CD Monitoring & Alerting

on:
  workflow_run:
    workflows: ["CI/CD Quality Gates"]
    types: [completed]
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  issues: write

jobs:
  pipeline-health-monitoring:
    name: "Pipeline Health Monitoring"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Analyze Pipeline Health
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "📊 Analyzing CI/CD pipeline health..."
          
          # Get recent workflow runs
          WORKFLOW_RUNS=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci-quality-gates.yml/runs?per_page=50")
          
          # Calculate success rate
          TOTAL_RUNS=$(echo "$WORKFLOW_RUNS" | jq '.workflow_runs | length')
          SUCCESS_RUNS=$(echo "$WORKFLOW_RUNS" | jq '[.workflow_runs[] | select(.conclusion == "success")] | length')
          
          if [[ $TOTAL_RUNS -gt 0 ]]; then
            SUCCESS_RATE=$((SUCCESS_RUNS * 100 / TOTAL_RUNS))
            echo "Pipeline success rate: $SUCCESS_RATE% ($SUCCESS_RUNS/$TOTAL_RUNS)"
            
            # Alert if success rate is below threshold
            if [[ $SUCCESS_RATE -lt 85 ]]; then
              echo "⚠️ Pipeline success rate below threshold (85%)"
              echo "PIPELINE_HEALTH_ALERT=true" >> $GITHUB_ENV
              echo "SUCCESS_RATE=$SUCCESS_RATE" >> $GITHUB_ENV
            else
              echo "✅ Pipeline health is good"
            fi
          else
            echo "ℹ️ No recent workflow runs found"
          fi

      - name: Flaky Test Detection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Analyzing test stability and detecting flaky tests..."
          
          # Get test results from recent runs
          RECENT_RUNS=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci-quality-gates.yml/runs?status=completed&per_page=20")
          
          # Analyze job failure patterns
          FAILED_JOBS=$(echo "$RECENT_RUNS" | jq -r '
            .workflow_runs[] | 
            select(.conclusion != "success") | 
            .jobs_url' | head -10)
          
          FLAKY_TESTS=()
          for job_url in $FAILED_JOBS; do
            if [[ -n "$job_url" ]]; then
              JOB_DETAILS=$(curl -s \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "$job_url")
              
              # Extract failed job names
              FAILED_JOB_NAMES=$(echo "$JOB_DETAILS" | jq -r '.jobs[] | select(.conclusion == "failure") | .name')
              
              while IFS= read -r job_name; do
                if [[ -n "$job_name" ]]; then
                  FLAKY_TESTS+=("$job_name")
                fi
              done <<< "$FAILED_JOB_NAMES"
            fi
          done
          
          # Count failures by job name
          if [[ ${#FLAKY_TESTS[@]} -gt 0 ]]; then
            echo "Potential flaky tests detected:"
            printf '%s\n' "${FLAKY_TESTS[@]}" | sort | uniq -c | sort -rn
            echo "FLAKY_TESTS_DETECTED=true" >> $GITHUB_ENV
          else
            echo "✅ No flaky tests detected"
          fi

      - name: Performance Regression Detection
        run: |
          echo "🚀 Checking for performance regressions..."
          
          # Download latest benchmark results if available
          if [[ -f benchmark-results.json ]]; then
            echo "📈 Analyzing current benchmark results..."
            
            # Extract key metrics
            CURRENT_METRICS=$(jq '.benchmarks[] | {name: .name, mean: .stats.mean}' benchmark-results.json)
            echo "Current performance metrics:"
            echo "$CURRENT_METRICS"
            
            # Check if we have baseline for comparison
            if [[ -f .ci/baseline-benchmarks.json ]]; then
              echo "📊 Comparing against baseline..."
              
              # Simple performance regression check
              # This would typically be more sophisticated in a real implementation
              echo "✅ Performance monitoring active"
            else
              echo "⚠️ No baseline benchmarks found for comparison"
            fi
          else
            echo "ℹ️ No benchmark results available"
          fi

      - name: Security Vulnerability Monitoring
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔐 Monitoring for security vulnerabilities..."
          
          # Check for security alerts
          SECURITY_ALERTS=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/vulnerability-alerts")
          
          # Check for dependabot alerts
          DEPENDABOT_ALERTS=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts?state=open")
          
          OPEN_ALERTS=$(echo "$DEPENDABOT_ALERTS" | jq length 2>/dev/null || echo "0")
          
          if [[ $OPEN_ALERTS -gt 0 ]]; then
            echo "⚠️ $OPEN_ALERTS open security alerts detected"
            echo "SECURITY_ALERTS_COUNT=$OPEN_ALERTS" >> $GITHUB_ENV
            echo "SECURITY_ALERT=true" >> $GITHUB_ENV
          else
            echo "✅ No open security alerts"
          fi

      - name: Coverage Trend Analysis
        run: |
          echo "📊 Analyzing code coverage trends..."
          
          # Check if we have current coverage data
          if [[ -f current-coverage.txt ]]; then
            CURRENT_COVERAGE=$(cat current-coverage.txt)
            echo "Current coverage: $CURRENT_COVERAGE%"
            
            # Check against baseline
            if [[ -f .ci/baseline-coverage.txt ]]; then
              BASELINE_COVERAGE=$(cat .ci/baseline-coverage.txt)
              COVERAGE_DIFF=$(echo "$CURRENT_COVERAGE - $BASELINE_COVERAGE" | bc -l 2>/dev/null || echo "0")
              
              echo "Coverage change: $COVERAGE_DIFF%"
              
              # Alert on significant coverage drops
              if (( $(echo "$COVERAGE_DIFF < -2" | bc -l) )); then
                echo "⚠️ Significant coverage drop detected"
                echo "COVERAGE_REGRESSION=true" >> $GITHUB_ENV
                echo "COVERAGE_DIFF=$COVERAGE_DIFF" >> $GITHUB_ENV
              fi
            fi
          else
            echo "ℹ️ No current coverage data available"
          fi

      - name: Create GitHub Issue for Alerts
        if: env.PIPELINE_HEALTH_ALERT == 'true' || env.FLAKY_TESTS_DETECTED == 'true' || env.SECURITY_ALERT == 'true' || env.COVERAGE_REGRESSION == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🚨 Creating GitHub issue for detected problems..."
          
          # Build issue body
          ISSUE_BODY="# CI/CD Pipeline Health Alert\n\n"
          ISSUE_BODY+="Generated on: $(date)\n"
          ISSUE_BODY+="Workflow: ${{ github.workflow }}\n"
          ISSUE_BODY+="Run ID: ${{ github.run_id }}\n\n"
          
          ISSUE_TITLE="CI/CD Health Alert: "
          ALERT_REASONS=()
          
          if [[ "$PIPELINE_HEALTH_ALERT" == "true" ]]; then
            ISSUE_BODY+="## 📉 Pipeline Success Rate Alert\n"
            ISSUE_BODY+="- Current success rate: ${SUCCESS_RATE}%\n"
            ISSUE_BODY+="- Threshold: 85%\n"
            ISSUE_BODY+="- Action required: Investigate recent failures\n\n"
            ALERT_REASONS+=("Low Success Rate")
          fi
          
          if [[ "$FLAKY_TESTS_DETECTED" == "true" ]]; then
            ISSUE_BODY+="## 🔄 Flaky Tests Detected\n"
            ISSUE_BODY+="- Multiple test failures detected\n"
            ISSUE_BODY+="- Action required: Review test stability\n\n"
            ALERT_REASONS+=("Flaky Tests")
          fi
          
          if [[ "$SECURITY_ALERT" == "true" ]]; then
            ISSUE_BODY+="## 🔐 Security Vulnerabilities\n"
            ISSUE_BODY+="- Open security alerts: ${SECURITY_ALERTS_COUNT}\n"
            ISSUE_BODY+="- Action required: Review and remediate vulnerabilities\n\n"
            ALERT_REASONS+=("Security Issues")
          fi
          
          if [[ "$COVERAGE_REGRESSION" == "true" ]]; then
            ISSUE_BODY+="## 📉 Coverage Regression\n"
            ISSUE_BODY+="- Coverage drop: ${COVERAGE_DIFF}%\n"
            ISSUE_BODY+="- Action required: Review recent changes\n\n"
            ALERT_REASONS+=("Coverage Drop")
          fi
          
          # Join alert reasons
          IFS=", "
          ISSUE_TITLE+="${ALERT_REASONS[*]}"
          
          ISSUE_BODY+="## 🔧 Recommended Actions\n"
          ISSUE_BODY+="1. Review the CI/CD pipeline logs\n"
          ISSUE_BODY+="2. Investigate failing tests and jobs\n"
          ISSUE_BODY+="3. Address any security vulnerabilities\n"
          ISSUE_BODY+="4. Monitor pipeline health metrics\n\n"
          ISSUE_BODY+="**This issue was automatically generated by the CI/CD monitoring system.**"
          
          # Create the issue
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues" \
            -d "{
              \"title\": \"$ISSUE_TITLE\",
              \"body\": \"$ISSUE_BODY\",
              \"labels\": [\"ci/cd\", \"monitoring\", \"alert\"]
            }"
          
          echo "✅ GitHub issue created for alerts"

      - name: Generate Monitoring Report
        run: |
          echo "📋 Generating comprehensive monitoring report..."
          
          cat > monitoring-report.md << 'EOF'
          # CI/CD Pipeline Monitoring Report
          
          Generated on: $(date)
          Workflow: ${{ github.workflow }}
          Run ID: ${{ github.run_id }}
          
          ## Pipeline Health Metrics
          
          - ✅ Success Rate: Monitored
          - ✅ Flaky Test Detection: Active
          - ✅ Performance Monitoring: Active
          - ✅ Security Monitoring: Active
          - ✅ Coverage Monitoring: Active
          
          ## Alert Thresholds
          
          - Pipeline Success Rate: ≥85%
          - Security Vulnerabilities: 0 open critical/high
          - Coverage Regression: <2% drop
          - Performance Regression: <10% degradation
          
          ## Monitoring Status
          
          All monitoring systems are operational and actively tracking pipeline health.
          Alerts will be automatically generated for any threshold violations.
          EOF
          
          echo "✅ Monitoring report generated"

      - name: Upload Monitoring Report
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-report
          path: monitoring-report.md
          retention-days: 30