name: performance-gate

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'libs/**'
      - 'scripts/nx-smart.mjs'
      - 'performance-baseline.json'
      - 'scripts/perf-check.mjs'
  workflow_dispatch: {}

jobs:
  perf:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.0
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build (metrics)
        run: node scripts/nx-smart.mjs build --metrics-json reports/build-metrics.json || true
      - name: Test (metrics)
        run: node scripts/nx-smart.mjs test --metrics-json reports/test-metrics.json || true
      - name: Lint (metrics)
        run: node scripts/nx-smart.mjs lint --metrics-json reports/lint-metrics.json || true
      - name: Typecheck (metrics)
        run: node scripts/nx-smart.mjs typecheck --metrics-json reports/typecheck-metrics.json || true
      - name: Performance Gates
        run: |
          node scripts/perf-check.mjs performance-baseline.json reports/build-metrics.json
          node scripts/perf-check.mjs performance-baseline.json reports/test-metrics.json
          node scripts/perf-check.mjs performance-baseline.json reports/lint-metrics.json
          node scripts/perf-check.mjs performance-baseline.json reports/typecheck-metrics.json
      - name: Upload Metrics Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: perf-metrics
          path: reports/*.json
