name: pr-light

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-signal:
    name: Quick PR Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.3.0

      - name: Install dependencies (frozen)
        run: pnpm install --frozen-lockfile

      - name: TypeScript typecheck (fast)
        run: pnpm security:typecheck

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Python deps
        run: |
          if command -v uv >/dev/null 2>&1; then uv sync; else python -m pip install --upgrade pip && pip install ruff; fi

      - name: Ruff lint (fast)
        run: pnpm python:lint

      - name: Semgrep high severity gate
        run: |
          semgrep scan --config=.semgrep/owasp-precise.yaml --severity=ERROR . --max-memory=2048 --timeout 180 --max-target-bytes 200MB --exclude reports --exclude coverage

      - name: AST-Grep (changed files only)
        run: |
          mkdir -p reports || true
          # Get changed files in PR (against base)
          git fetch origin "${{ github.base_ref }}" --depth=1 || true
          BASE_SHA=$(git rev-parse "origin/${{ github.base_ref }}" || echo HEAD)
          CHANGED=$(git diff --name-only "$BASE_SHA" | grep -E '\.(ts|tsx|js|jsx)$' || true)
          if [ -n "$CHANGED" ]; then
            echo "$CHANGED" | xargs -n 50 ast-grep scan --config sgconfig.json --json >> reports/ast-grep-pr.json || true
          else
            echo "No changed TS/JS files for ast-grep"
          fi
          if [ -f reports/ast-grep-pr.json ]; then
            echo "AST-Grep PR JSON saved"
          fi

      - name: Upload AST-Grep PR report
        if: ${{ hashFiles('reports/ast-grep-pr.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: ast-grep-pr
          path: reports/ast-grep-pr.json
