name: readiness
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  readiness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Generate readiness.yml files (if missing)
        run: node tools/readiness/generate-readiness-yml.mjs
      - name: Run package tests with coverage (per package)
        run: node tools/readiness/run-package-tests.mjs
      - name: Enforce coverage thresholds per package (>=95%)
        run: node tools/readiness/check-readiness.mjs
