name: SBOM

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: astral-sh/setup-uv@v3
      - run: pnpm install --frozen-lockfile
      - name: Generate SBOM
        run: pnpm sbom:generate
      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: |
            sbom-node.json
            sbom-python.json
            sbom-unified.json
