name: Security

on:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
        with:
          version: 9

      - uses: astral-sh/setup-uv@8d55fbecc275b1c35dbe060458839f8d30439ccf
      - run: pnpm install --frozen-lockfile
      - name: npm audit (moderate as advisory)
        run: |
          pnpm audit --audit-level=moderate
      - name: OSV scan
        uses: google/osv-scanner-action@c0e8a1142dcb3ae443d26c8f6a2b774db9f6c6ea
        with:
          scan-args: --lockfile=pnpm-lock.yaml
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8

        with:
          version: 10.13.1
      - name: Install Semgrep
        run: pipx install semgrep==1.132.0
      - name: Check for security scan prerequisites
        id: check_security_scan
        run: |
          if [ ! -d "scripts/security" ]; then
            echo "scripts/security directory does not exist. Skipping security scan."
            echo "scan_exists=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          if ! grep -q '"security:scan:errors"' package.json; then
            echo "security:scan:errors script not found in package.json. Skipping security scan."
            echo "scan_exists=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "scan_exists=true" >> $GITHUB_OUTPUT

      - name: Run security scan
        if: steps.check_security_scan.outputs.scan_exists == 'true'
        working-directory: scripts/security
        run: pnpm security:scan:errors
      - name: Validate security fixes
        run: |

          uv run safety check --json
      - name: Upload Bandit JSON report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: bandit-report
          path: bandit-report.json

