name: Security
on:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
jobs:
  supply-chain:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: astral-sh/setup-uv@v3
      - run: pnpm install --frozen-lockfile
      - name: npm audit (moderate as advisory)
        run: |
          pnpm audit --audit-level=moderate
      - name: OSV scan
        uses: google/osv-scanner-action@v1
        with:
          scan-args: --lockfile=pnpm-lock.yaml
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
      - name: Upload Trivy SARIF if present
        if: always()
        run: |
          if [ -f trivy-results.sarif ]; then
            echo "Uploading trivy-results.sarif"
          else
            echo "No trivy SARIF produced"
            exit 0
          fi
      - name: Upload SARIF via action (if present)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
      - name: Python checks (bandit, safety)
        run: |
          uv pip install --upgrade bandit[toml] safety
          uv run bandit -r services/ -f json -o bandit-report.json
          uv run safety check --json
