name: Security - SCA, Sigstore signing & verification

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependency-scan:
    name: Dependency & Supply Chain Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (pnpm)
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          export PATH="$HOME/.local/share/pnpm:$PATH"
          pnpm install --frozen-lockfile

      - name: Run npm audit
        run: pnpm audit --audit-level=moderate || true

      - name: Run snyk (optional)
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: snyk/actions/node@master
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Python pip-audit
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit

      - name: Run pip-audit (repo wide)
        run: |
          if [ -f pyproject.toml ] || [ -f requirements.txt ]; then
            pip-audit || true
          else
            echo "No python deps detected"
          fi

      - name: OSS Index scan (optional)
        if: ${{ secrets.OSSINDEX_API_TOKEN != '' }}
        run: |
          echo "OSS Index scan placeholder - implement per-repo scripting or use a community action"

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: sca-reports
          path: |
            pnpm-lock.yaml
            pip-audit-results.txt

  build-and-sign:
    name: Build, sign artifacts with Sigstore (cosign)
    runs-on: ubuntu-latest
    needs: dependency-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm and build
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          export PATH="$HOME/.local/share/pnpm:$PATH"
          pnpm install --frozen-lockfile
          pnpm build || true

      - name: Install cosign
        run: |
          COSIGN_VERSION=2.3.0
          curl -sLO "https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-amd64"
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Sign build artifacts with cosign (OIDC)
        env:
          COSIGN_EXPERIMENTAL: '1'
        run: |
          # Sign core lockfiles and build output
          ARTIFACTS="pnpm-lock.yaml"
          for f in $ARTIFACTS; do
            if [ -f "$f" ]; then
              cosign sign --oidc --output-signature "$f.sig" "$f" || true
            fi
          done

      - name: Upload signed artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-artifacts
          path: |
            pnpm-lock.yaml.sig
            pnpm-lock.yaml

  verify-signature:
    name: Verify signatures (provenance)
    runs-on: ubuntu-latest
    needs: build-and-sign
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cosign
        run: |
          COSIGN_VERSION=2.3.0
          curl -sLO "https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-amd64"
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Download signed artifacts
        uses: actions/download-artifact@v4
        with:
          name: signed-artifacts

      - name: Verify signature
        run: |
          if [ -f pnpm-lock.yaml.sig ]; then
            cosign verify-blob --key ${{ secrets.COSIGN_PUBKEY }} --signature pnpm-lock.yaml.sig pnpm-lock.yaml || exit 1
          else
            echo "No signature found to verify"
            exit 1
          fi
