name: Security

on:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      - name: Install Semgrep
        run: pipx install semgrep==1.132.0
      - name: Check for security scan prerequisites
        id: check_security_scan
        run: |
          if [ ! -d "scripts/security" ]; then
            echo "scripts/security directory does not exist. Skipping security scan."
            echo "scan_exists=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          if ! grep -q '"security:scan:errors"' package.json; then
            echo "security:scan:errors script not found in package.json. Skipping security scan."
            echo "scan_exists=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "scan_exists=true" >> $GITHUB_OUTPUT

      - name: Run security scan
        if: steps.check_security_scan.outputs.scan_exists == 'true'
        working-directory: scripts/security
        run: pnpm security:scan:errors
      - name: Validate security fixes
        working-directory: scripts/security
        run: pnpm security:validate
