name: Security Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  supply-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: NPM Audit
        run: pnpm security:audit
      - name: OSS Index Audit
        run: pnpm dlx auditjs ossi --project-name cortex-os
      - uses: sigstore/cosign-installer@v3.4.0
      - name: Sign lockfile
        run: cosign sign-blob --yes pnpm-lock.yaml --output-signature pnpm-lock.yaml.sig --output-certificate pnpm-lock.yaml.pem
      - name: Verify lockfile signature
        run: cosign verify-blob pnpm-lock.yaml --signature pnpm-lock.yaml.sig --certificate pnpm-lock.yaml.pem

  dast:
    runs-on: ubuntu-latest
    env:
      TARGET_URL: ${{ secrets.DAST_TARGET_URL }}
    steps:
      - name: OWASP ZAP baseline
        run: docker run --rm owasp/zap2docker-stable zap-baseline.py -t $TARGET_URL -I -r zap-report.html
