name: Semgrep
on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '5 3 * * *'
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Semgrep
        run: pipx install semgrep || pip install semgrep --break-system-packages || true
      - name: Run Semgrep
        run: |
          semgrep scan \
            --config .semgrep/owasp-precise.yaml \
            --config .semgrep/owasp-top-10-improved.yaml \
            --no-error \
            --sarif -o semgrep.sarif .
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
