name: Semgrep
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: ./.semgrep.yml
