name: Semgrep
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:

          config: |
            .semgrep/owasp-llm-top-ten.yaml
            .semgrep/mitre-atlas.yaml
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

