name: Semgrep
on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '5 3 * * *'
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --filter @cortex-os/security...
      - name: Install Semgrep
        run: |
          if ! pipx install semgrep; then
            python -m pip install --user semgrep || { echo "Failed to install semgrep"; exit 1; }
          fi
      - name: Run Semgrep
        run: pnpm -F @cortex-os/security semgrep
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: packages/security/semgrep.sarif
