name: Unified Security (MIGRATED)

# MIGRATION NOTICE:
# This workflow has been replaced by `security-modern.yml` which provides
# the same functionality with improved performance and better organization.
# This workflow now redirects to the new implementation.

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1' # Weekly deep scan (Mondays 03:00 UTC)

concurrency:
  group: unified-security-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  redirect-to-modern:
    name: Redirect to Security Modern
    uses: ./.github/workflows/security-modern.yml
