name: verify
on: [push, pull_request]
jobs:
  toolchains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        run: |
          curl -fsSL https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: mise --version
      - run: mise install
      - run: node -v && pnpm -v && python --version && rustc -V
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -fsSL https://mise.run | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: mise install
      - run: corepack enable && pnpm install --frozen-lockfile
      - run: pnpm nx run-many -t lint typecheck test build --parallel
      - run: cargo fmt --manifest-path=./Cargo.toml -- --check && cargo clippy --manifest-path=./Cargo.toml -- -D warnings
