[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cortex-mcp-chatgpt-connector"
version = "1.0.0"
description = "ChatGPT Connector MCP Server for Cortex-OS - Second Brain Integration"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [{ name = "brAInwav Cortex-OS Team", email = "jscraik@brainwav.io" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.12"

dependencies = [
  # Core MCP dependencies (inherited from parent package)
  "cortex-mcp>=1.0.0",

  # OpenAI integration
  "openai>=1.50.0",

  # Web framework
  "fastapi>=0.104.0",
  "uvicorn[standard]>=0.24.0",

  # Configuration
  "python-dotenv>=1.0.0",
]

[project.scripts]
mcp-chatgpt-connector = "mcp_servers.chatgpt_connector.server:main"
mcp-chatgpt-connector-sse = "mcp_servers.chatgpt_connector.mcp_sse_server:main"

[project.optional-dependencies]
dev = ["pytest>=7.4.3", "pytest-asyncio>=0.21.1", "pytest-cov>=4.1.0"]

[project.urls]
Homepage = "https://github.com/cortex-os/cortex-mcp"
Repository = "https://github.com/cortex-os/cortex-mcp"
Documentation = "https://docs.cortex-os.ai/mcp/chatgpt-connector"
Issues = "https://github.com/cortex-os/cortex-mcp/issues"

[tool.hatch.build.targets.wheel]
packages = ["mcp_servers/chatgpt_connector"]

[tool.hatch.metadata]
allow-direct-references = true
